//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address: 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Advanced... 的本地化字符串。
        /// </summary>
        public static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alter ID: 的本地化字符串。
        /// </summary>
        public static string alterId {
            get {
                return ResourceManager.GetString("alterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Autostart on windows 的本地化字符串。
        /// </summary>
        public static string autoStart {
            get {
                return ResourceManager.GetString("autoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse config folder... 的本地化字符串。
        /// </summary>
        public static string browseconfig {
            get {
                return ResourceManager.GetString("browseconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/overview.html 的本地化字符串。
        /// </summary>
        public static string configHelppage {
            get {
                return ResourceManager.GetString("configHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To fully take control of the V2Ray core, directly put config files (JSON) in the config folder located at the same folder as V2RayW.exe. 的本地化字符串。
        /// </summary>
        public static string configInstruction {
            get {
                return ResourceManager.GetString("configInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure... 的本地化字符串。
        /// </summary>
        public static string configure {
            get {
                return ResourceManager.GetString("configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayW Configure 的本地化字符串。
        /// </summary>
        public static string configWindowName {
            get {
                return ResourceManager.GetString("configWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congestion: 的本地化字符串。
        /// </summary>
        public static string congestion {
            get {
                return ResourceManager.GetString("congestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/welcome/install.html 的本地化字符串。
        /// </summary>
        public static string coreHelppage {
            get {
                return ResourceManager.GetString("coreHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-core: loaded 的本地化字符串。
        /// </summary>
        public static string coreloaded {
            get {
                return ResourceManager.GetString("coreloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-core: unloaded 的本地化字符串。
        /// </summary>
        public static string coreunloaded {
            get {
                return ResourceManager.GetString("coreunloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Encryption 的本地化字符串。
        /// </summary>
        public static string customizeencryption {
            get {
                return ResourceManager.GetString("customizeencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize Flow 的本地化字符串。
        /// </summary>
        public static string customizeflow {
            get {
                return ResourceManager.GetString("customizeflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize HTTP Header 的本地化字符串。
        /// </summary>
        public static string customizehttpheader {
            get {
                return ResourceManager.GetString("customizehttpheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If local ports are changed, PAC files also need modifications. 的本地化字符串。
        /// </summary>
        public static string DNSInstruction {
            get {
                return ResourceManager.GetString("DNSInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 domain/IP 的本地化字符串。
        /// </summary>
        public static string domainIp {
            get {
                return ResourceManager.GetString("domainIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain Strategy: 的本地化字符串。
        /// </summary>
        public static string DomainStrategy {
            get {
                return ResourceManager.GetString("DomainStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downlink capacity: 的本地化字符串。
        /// </summary>
        public static string dowlonkcapacity {
            get {
                return ResourceManager.GetString("dowlonkcapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit PAC 的本地化字符串。
        /// </summary>
        public static string editpac {
            get {
                return ResourceManager.GetString("editpac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Mux 的本地化字符串。
        /// </summary>
        public static string enableMux {
            get {
                return ResourceManager.GetString("enableMux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2fly.org/config/protocols/vless.html#outboundconfigurationobject 的本地化字符串。
        /// </summary>
        public static string encryptionHelpPage {
            get {
                return ResourceManager.GetString("encryptionHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhanced... 的本地化字符串。
        /// </summary>
        public static string enhanced {
            get {
                return ResourceManager.GetString("enhanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Example: 的本地化字符串。
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export/Backup 的本地化字符串。
        /// </summary>
        public static string exportbackup {
            get {
                return ResourceManager.GetString("exportbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2fly.org/config/protocols/vless.html#xtls-%E9%BB%91%E7%A7%91%E6%8A%80 的本地化字符串。
        /// </summary>
        public static string flowHelpPage {
            get {
                return ResourceManager.GetString("flowHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force TCP Fast Open 的本地化字符串。
        /// </summary>
        public static string ForceTcpFastOpen {
            get {
                return ResourceManager.GetString("ForceTcpFastOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Mode 的本地化字符串。
        /// </summary>
        public static string globalmode {
            get {
                return ResourceManager.GetString("globalmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header: 的本地化字符串。
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Header type: 的本地化字符串。
        /// </summary>
        public static string headertype {
            get {
                return ResourceManager.GetString("headertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host: 的本地化字符串。
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import... 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import from clipboard 的本地化字符串。
        /// </summary>
        public static string ImportClipboard {
            get {
                return ResourceManager.GetString("ImportClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import form subscribe 的本地化字符串。
        /// </summary>
        public static string ImportSubscribe {
            get {
                return ResourceManager.GetString("ImportSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key: 的本地化字符串。
        /// </summary>
        public static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level: 的本地化字符串。
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple values should be seperated by comma(,). No spaces. 的本地化字符串。
        /// </summary>
        public static string ListInstruction {
            get {
                return ResourceManager.GetString("ListInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Core 的本地化字符串。
        /// </summary>
        public static string loadcore {
            get {
                return ResourceManager.GetString("loadcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local HTTP Port: 的本地化字符串。
        /// </summary>
        public static string LocalHTTPPort {
            get {
                return ResourceManager.GetString("LocalHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Socks5 Port: 的本地化字符串。
        /// </summary>
        public static string LocalSocks5Port {
            get {
                return ResourceManager.GetString("LocalSocks5Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log level: 的本地化字符串。
        /// </summary>
        public static string loglevel {
            get {
                return ResourceManager.GetString("loglevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Mode 的本地化字符串。
        /// </summary>
        public static string manualmode {
            get {
                return ResourceManager.GetString("manualmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray exits unexpectedly! 的本地化字符串。
        /// </summary>
        public static string messagecorequit {
            get {
                return ResourceManager.GetString("messagecorequit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create folder(s)! 的本地化字符串。
        /// </summary>
        public static string messagedircreatefail {
            get {
                return ResourceManager.GetString("messagedircreatefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayW cannot download V2Ray core! 的本地化字符串。
        /// </summary>
        public static string messagedownloadfail {
            get {
                return ResourceManager.GetString("messagedownloadfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayW is downloading V2Ray core from GitHub. 的本地化字符串。
        /// </summary>
        public static string messagedownloading {
            get {
                return ResourceManager.GetString("messagedownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayW got V2Ray core from GitHub. 的本地化字符串。
        /// </summary>
        public static string messagedownloadsuccess {
            get {
                return ResourceManager.GetString("messagedownloadsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot create file(s)! 的本地化字符串。
        /// </summary>
        public static string messagefilecreatefail {
            get {
                return ResourceManager.GetString("messagefilecreatefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Let V2RayW doanload V2Ray from GitHub?
        ///“Yes”：V2RayW will try downloading V2Ray from GitHub。
        ///“No”：Manually download V2Ray and put files into folder v2ray-core.
        ///“Cancel”：Quit V2RayW。
        ///
        ///Folder v2ray-core should be put in the same folder as V2RayW.exe. The following files should be contained in v2ray-core:
        ///v2ray-core\v2ray.exe
        ///v2ray-core\v2ctl.exe
        ///v2ray-core\geoip.dat
        ///v2ray-core\geosite.dat 的本地化字符串。
        /// </summary>
        public static string messagenocore {
            get {
                return ResourceManager.GetString("messagenocore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot find V2Ray! 的本地化字符串。
        /// </summary>
        public static string messagenocoretitle {
            get {
                return ResourceManager.GetString("messagenocoretitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available servers. 的本地化字符串。
        /// </summary>
        public static string messagenoserver {
            get {
                return ResourceManager.GetString("messagenoserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not a valid JSON! 的本地化字符串。
        /// </summary>
        public static string messagenotvalidjson {
            get {
                return ResourceManager.GetString("messagenotvalidjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayW encounters errors while reading settings. 的本地化字符串。
        /// </summary>
        public static string messagereaddefaultserror {
            get {
                return ResourceManager.GetString("messagereaddefaultserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;tag&quot; is requried! 的本地化字符串。
        /// </summary>
        public static string messagetagrequired {
            get {
                return ResourceManager.GetString("messagetagrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MTU: 的本地化字符串。
        /// </summary>
        public static string mtu {
            get {
                return ResourceManager.GetString("mtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mux concurrency: 的本地化字符串。
        /// </summary>
        public static string Muxconcurrency {
            get {
                return ResourceManager.GetString("Muxconcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/mux.html 的本地化字符串。
        /// </summary>
        public static string muxHelpPage {
            get {
                return ResourceManager.GetString("muxHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network: 的本地化字符串。
        /// </summary>
        public static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/overview.html#outboundobject 的本地化字符串。
        /// </summary>
        public static string outboundHelppage {
            get {
                return ResourceManager.GetString("outboundHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To use outbounds of other protocols apart from vmess, directly provide the corresponding OutboundObject below. Click Help to see instructions. 的本地化字符串。
        /// </summary>
        public static string outboundInstruction {
            get {
                return ResourceManager.GetString("outboundInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outbounds 的本地化字符串。
        /// </summary>
        public static string Outbounds {
            get {
                return ResourceManager.GetString("Outbounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC list 的本地化字符串。
        /// </summary>
        public static string paclist {
            get {
                return ResourceManager.GetString("paclist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAC Mode 的本地化字符串。
        /// </summary>
        public static string pacmode {
            get {
                return ResourceManager.GetString("pacmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path: 的本地化字符串。
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QUIC is now an experiment in V2Ray. It implements IETF specification. As the spec is still being standardized, compatibility can&apos;t be guaranteed. 的本地化字符串。
        /// </summary>
        public static string quicstatement {
            get {
                return ResourceManager.GetString("quicstatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quit 的本地化字符串。
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read buffer size 的本地化字符串。
        /// </summary>
        public static string readsize {
            get {
                return ResourceManager.GetString("readsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset All 的本地化字符串。
        /// </summary>
        public static string resetall {
            get {
                return ResourceManager.GetString("resetall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset pac file 的本地化字符串。
        /// </summary>
        public static string resetpacfile {
            get {
                return ResourceManager.GetString("resetpacfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turn off system proxy 的本地化字符串。
        /// </summary>
        public static string RestoreTurnOff {
            get {
                return ResourceManager.GetString("RestoreTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore system proxy to original states 的本地化字符串。
        /// </summary>
        public static string RestoreTurnOn {
            get {
                return ResourceManager.GetString("RestoreTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 route to: 的本地化字符串。
        /// </summary>
        public static string routeto {
            get {
                return ResourceManager.GetString("routeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray&apos;s Routing rule... 的本地化字符串。
        /// </summary>
        public static string routingrule {
            get {
                return ResourceManager.GetString("routingrule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/routing.html 的本地化字符串。
        /// </summary>
        public static string ruleHelppage {
            get {
                return ResourceManager.GetString("ruleHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bypass cn&amp;private 的本地化字符串。
        /// </summary>
        public static string rulenamebypass {
            get {
                return ResourceManager.GetString("rulenamebypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 all to direct 的本地化字符串。
        /// </summary>
        public static string rulenamedirect {
            get {
                return ResourceManager.GetString("rulenamedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 all to main 的本地化字符串。
        /// </summary>
        public static string rulenameglobal {
            get {
                return ResourceManager.GetString("rulenameglobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 network 的本地化字符串。
        /// </summary>
        public static string rulenetwork {
            get {
                return ResourceManager.GetString("rulenetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 port 的本地化字符串。
        /// </summary>
        public static string ruleport {
            get {
                return ResourceManager.GetString("ruleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules 的本地化字符串。
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Set Name: 的本地化字符串。
        /// </summary>
        public static string rulseSetName {
            get {
                return ResourceManager.GetString("rulseSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security: 的本地化字符串。
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 See example 的本地化字符串。
        /// </summary>
        public static string seeexample {
            get {
                return ResourceManager.GetString("seeexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server... 的本地化字符串。
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server Information 的本地化字符串。
        /// </summary>
        public static string ServerInfo {
            get {
                return ResourceManager.GetString("ServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share 的本地化字符串。
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Share Over LAN 的本地化字符串。
        /// </summary>
        public static string ShareOverLan {
            get {
                return ResourceManager.GetString("ShareOverLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Log 的本地化字符串。
        /// </summary>
        public static string showlog {
            get {
                return ResourceManager.GetString("showlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed Test 的本地化字符串。
        /// </summary>
        public static string speedtest {
            get {
                return ResourceManager.GetString("speedtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The independent process implements the speed test function without affecting the current configuration. 的本地化字符串。
        /// </summary>
        public static string speedtesttip {
            get {
                return ResourceManager.GetString("speedtesttip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription 的本地化字符串。
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save your airport subscription link here, and select subscription from the configuration interface import from to refresh the server configuration. 的本地化字符串。
        /// </summary>
        public static string SubscriptionInstruction {
            get {
                return ResourceManager.GetString("SubscriptionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag: 的本地化字符串。
        /// </summary>
        public static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/transport/tcp.html#httpheaderobject 的本地化字符串。
        /// </summary>
        public static string tcpHelpPage {
            get {
                return ResourceManager.GetString("tcpHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow insecure certificates 的本地化字符串。
        /// </summary>
        public static string TLSallowInsecure {
            get {
                return ResourceManager.GetString("TLSallowInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow insecure ciphers 的本地化字符串。
        /// </summary>
        public static string TLSallowInsecureCiphers {
            get {
                return ResourceManager.GetString("TLSallowInsecureCiphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ALPN: 的本地化字符串。
        /// </summary>
        public static string tlsalpn {
            get {
                return ResourceManager.GetString("tlsalpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server name: 的本地化字符串。
        /// </summary>
        public static string TLSserverName {
            get {
                return ResourceManager.GetString("TLSserverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.v2ray.com/en/configuration/transport.html 的本地化字符串。
        /// </summary>
        public static string transportHelpPage {
            get {
                return ResourceManager.GetString("transportHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport settings... 的本地化字符串。
        /// </summary>
        public static string transportsettings {
            get {
                return ResourceManager.GetString("transportsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TTI: 的本地化字符串。
        /// </summary>
        public static string tti {
            get {
                return ResourceManager.GetString("tti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UDP Support 的本地化字符串。
        /// </summary>
        public static string UDPSupport {
            get {
                return ResourceManager.GetString("UDPSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unload Core 的本地化字符串。
        /// </summary>
        public static string unloadcore {
            get {
                return ResourceManager.GetString("unloadcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update subscription 的本地化字符串。
        /// </summary>
        public static string updatesubscription {
            get {
                return ResourceManager.GetString("updatesubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uplink capacity: 的本地化字符串。
        /// </summary>
        public static string uplinkcapacity {
            get {
                return ResourceManager.GetString("uplinkcapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use All 的本地化字符串。
        /// </summary>
        public static string useall {
            get {
                return ResourceManager.GetString("useall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User ID: 的本地化字符串。
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use TLS 的本地化字符串。
        /// </summary>
        public static string usetls {
            get {
                return ResourceManager.GetString("usetls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray Core 的本地化字符串。
        /// </summary>
        public static string V2RayCore {
            get {
                return ResourceManager.GetString("V2RayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://v2ray.com/en/index.html 的本地化字符串。
        /// </summary>
        public static string V2RayHomePage {
            get {
                return ResourceManager.GetString("V2RayHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray Servers 的本地化字符串。
        /// </summary>
        public static string V2RayServers {
            get {
                return ResourceManager.GetString("V2RayServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Valid config files: 的本地化字符串。
        /// </summary>
        public static string validConfig {
            get {
                return ResourceManager.GetString("validConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View current config.json 的本地化字符串。
        /// </summary>
        public static string viewconfig {
            get {
                return ResourceManager.GetString("viewconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write buffer size 的本地化字符串。
        /// </summary>
        public static string writesize {
            get {
                return ResourceManager.GetString("writesize", resourceCulture);
            }
        }
    }
}
