//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayW.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        public static string advanced {
            get {
                return ResourceManager.GetString("advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alter ID:.
        /// </summary>
        public static string alterId {
            get {
                return ResourceManager.GetString("alterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse config folder....
        /// </summary>
        public static string browseconfig {
            get {
                return ResourceManager.GetString("browseconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/overview.html.
        /// </summary>
        public static string configHelppage {
            get {
                return ResourceManager.GetString("configHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To fully take control of the V2Ray core, directly put config files (JSON) in the config folder located at the same folder as V2RayW.exe..
        /// </summary>
        public static string configInstruction {
            get {
                return ResourceManager.GetString("configInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure....
        /// </summary>
        public static string configure {
            get {
                return ResourceManager.GetString("configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2RayW Configure.
        /// </summary>
        public static string configWindowName {
            get {
                return ResourceManager.GetString("configWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congestion:.
        /// </summary>
        public static string congestion {
            get {
                return ResourceManager.GetString("congestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/welcome/install.html.
        /// </summary>
        public static string coreHelppage {
            get {
                return ResourceManager.GetString("coreHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2ray-core: loaded.
        /// </summary>
        public static string coreloaded {
            get {
                return ResourceManager.GetString("coreloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2ray-core: unloaded.
        /// </summary>
        public static string coreunloaded {
            get {
                return ResourceManager.GetString("coreunloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize HTTP Header.
        /// </summary>
        public static string customizehttpheader {
            get {
                return ResourceManager.GetString("customizehttpheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If local ports are changed, PAC files also need modifications..
        /// </summary>
        public static string DNSInstruction {
            get {
                return ResourceManager.GetString("DNSInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domain/IP.
        /// </summary>
        public static string domainIp {
            get {
                return ResourceManager.GetString("domainIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Strategy:.
        /// </summary>
        public static string DomainStrategy {
            get {
                return ResourceManager.GetString("DomainStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downlink capacity:.
        /// </summary>
        public static string dowlonkcapacity {
            get {
                return ResourceManager.GetString("dowlonkcapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PAC.
        /// </summary>
        public static string editpac {
            get {
                return ResourceManager.GetString("editpac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Mux.
        /// </summary>
        public static string enableMux {
            get {
                return ResourceManager.GetString("enableMux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        public static string Example {
            get {
                return ResourceManager.GetString("Example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/Backup.
        /// </summary>
        public static string exportbackup {
            get {
                return ResourceManager.GetString("exportbackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force TCP Fast Open.
        /// </summary>
        public static string ForceTcpFastOpen {
            get {
                return ResourceManager.GetString("ForceTcpFastOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Mode.
        /// </summary>
        public static string globalmode {
            get {
                return ResourceManager.GetString("globalmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header:.
        /// </summary>
        public static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header type:.
        /// </summary>
        public static string headertype {
            get {
                return ResourceManager.GetString("headertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host:.
        /// </summary>
        public static string host {
            get {
                return ResourceManager.GetString("host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple values should be seperated by comma(,). No spaces..
        /// </summary>
        public static string ListInstruction {
            get {
                return ResourceManager.GetString("ListInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Core.
        /// </summary>
        public static string loadcore {
            get {
                return ResourceManager.GetString("loadcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local HTTP Port:.
        /// </summary>
        public static string LocalHTTPPort {
            get {
                return ResourceManager.GetString("LocalHTTPPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Socks5 Port:.
        /// </summary>
        public static string LocalSocks5Port {
            get {
                return ResourceManager.GetString("LocalSocks5Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level:.
        /// </summary>
        public static string loglevel {
            get {
                return ResourceManager.GetString("loglevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mode.
        /// </summary>
        public static string manualmode {
            get {
                return ResourceManager.GetString("manualmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2Ray exits unexpectedly!.
        /// </summary>
        public static string messagecorequit {
            get {
                return ResourceManager.GetString("messagecorequit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create folder(s)!.
        /// </summary>
        public static string messagedircreatefail {
            get {
                return ResourceManager.GetString("messagedircreatefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2RayW cannot download V2Ray core!.
        /// </summary>
        public static string messagedownloadfail {
            get {
                return ResourceManager.GetString("messagedownloadfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2RayW is downloading V2Ray core from GitHub..
        /// </summary>
        public static string messagedownloading {
            get {
                return ResourceManager.GetString("messagedownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2RayW got V2Ray core from GitHub..
        /// </summary>
        public static string messagedownloadsuccess {
            get {
                return ResourceManager.GetString("messagedownloadsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create file(s)!.
        /// </summary>
        public static string messagefilecreatefail {
            get {
                return ResourceManager.GetString("messagefilecreatefail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let V2RayW doanload V2Ray from GitHub?
        ///“Yes”：V2RayW will try downloading V2Ray from GitHub。
        ///“No”：Manually download V2Ray and put files into folder v2ray-core.
        ///“Cancel”：Quit V2RayW。
        ///
        ///Folder v2ray-core should be put in the same folder as V2RayW.exe. The following files should be contained in v2ray-core:
        ///v2ray-core\v2ray.exe
        ///v2ray-core\v2ctl.exe
        ///v2ray-core\geoip.dat
        ///v2ray-core\geosite.dat.
        /// </summary>
        public static string messagenocore {
            get {
                return ResourceManager.GetString("messagenocore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find V2Ray!.
        /// </summary>
        public static string messagenocoretitle {
            get {
                return ResourceManager.GetString("messagenocoretitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available servers..
        /// </summary>
        public static string messagenoserver {
            get {
                return ResourceManager.GetString("messagenoserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid JSON!.
        /// </summary>
        public static string messagenotvalidjson {
            get {
                return ResourceManager.GetString("messagenotvalidjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2RayW encounters errors while reading settings..
        /// </summary>
        public static string messagereaddefaultserror {
            get {
                return ResourceManager.GetString("messagereaddefaultserror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;tag&quot; is requried!.
        /// </summary>
        public static string messagetagrequired {
            get {
                return ResourceManager.GetString("messagetagrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTU:.
        /// </summary>
        public static string mtu {
            get {
                return ResourceManager.GetString("mtu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mux concurrency:.
        /// </summary>
        public static string Muxconcurrency {
            get {
                return ResourceManager.GetString("Muxconcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/mux.html.
        /// </summary>
        public static string muxHelpPage {
            get {
                return ResourceManager.GetString("muxHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network:.
        /// </summary>
        public static string network {
            get {
                return ResourceManager.GetString("network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/overview.html#outboundobject.
        /// </summary>
        public static string outboundHelppage {
            get {
                return ResourceManager.GetString("outboundHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use outbounds of other protocols apart from vmess, directly provide the corresponding OutboundObject below. Click Help to see instructions..
        /// </summary>
        public static string outboundInstruction {
            get {
                return ResourceManager.GetString("outboundInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outbounds.
        /// </summary>
        public static string Outbounds {
            get {
                return ResourceManager.GetString("Outbounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC list.
        /// </summary>
        public static string paclist {
            get {
                return ResourceManager.GetString("paclist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC Mode.
        /// </summary>
        public static string pacmode {
            get {
                return ResourceManager.GetString("pacmode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIC is now an experiment in V2Ray. It implements IETF specification. As the spec is still being standardized, compatibility can&apos;t be guaranteed..
        /// </summary>
        public static string quicstatement {
            get {
                return ResourceManager.GetString("quicstatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string quit {
            get {
                return ResourceManager.GetString("quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read buffer size.
        /// </summary>
        public static string readsize {
            get {
                return ResourceManager.GetString("readsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string resetall {
            get {
                return ResourceManager.GetString("resetall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset pac file.
        /// </summary>
        public static string resetpacfile {
            get {
                return ResourceManager.GetString("resetpacfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off system proxy.
        /// </summary>
        public static string RestoreTurnOff {
            get {
                return ResourceManager.GetString("RestoreTurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore system proxy to original states.
        /// </summary>
        public static string RestoreTurnOn {
            get {
                return ResourceManager.GetString("RestoreTurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route to:.
        /// </summary>
        public static string routeto {
            get {
                return ResourceManager.GetString("routeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2Ray&apos;s Routing rule....
        /// </summary>
        public static string routingrule {
            get {
                return ResourceManager.GetString("routingrule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/routing.html.
        /// </summary>
        public static string ruleHelppage {
            get {
                return ResourceManager.GetString("ruleHelppage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bypass cn&amp;private.
        /// </summary>
        public static string rulenamebypass {
            get {
                return ResourceManager.GetString("rulenamebypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all to direct.
        /// </summary>
        public static string rulenamedirect {
            get {
                return ResourceManager.GetString("rulenamedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all to main.
        /// </summary>
        public static string rulenameglobal {
            get {
                return ResourceManager.GetString("rulenameglobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network.
        /// </summary>
        public static string rulenetwork {
            get {
                return ResourceManager.GetString("rulenetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port.
        /// </summary>
        public static string ruleport {
            get {
                return ResourceManager.GetString("ruleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Set Name:.
        /// </summary>
        public static string rulseSetName {
            get {
                return ResourceManager.GetString("rulseSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security:.
        /// </summary>
        public static string security {
            get {
                return ResourceManager.GetString("security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See example.
        /// </summary>
        public static string seeexample {
            get {
                return ResourceManager.GetString("seeexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server....
        /// </summary>
        public static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        public static string ServerInfo {
            get {
                return ResourceManager.GetString("ServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Over LAN.
        /// </summary>
        public static string ShareOverLan {
            get {
                return ResourceManager.GetString("ShareOverLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Log.
        /// </summary>
        public static string showlog {
            get {
                return ResourceManager.GetString("showlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription.
        /// </summary>
        public static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        public static string tag {
            get {
                return ResourceManager.GetString("tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/transport/tcp.html#httpheaderobject.
        /// </summary>
        public static string tcpHelpPage {
            get {
                return ResourceManager.GetString("tcpHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow insecure certificates.
        /// </summary>
        public static string TLSallowInsecure {
            get {
                return ResourceManager.GetString("TLSallowInsecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow insecure ciphers.
        /// </summary>
        public static string TLSallowInsecureCiphers {
            get {
                return ResourceManager.GetString("TLSallowInsecureCiphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALPN:.
        /// </summary>
        public static string tlsalpn {
            get {
                return ResourceManager.GetString("tlsalpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name:.
        /// </summary>
        public static string TLSserverName {
            get {
                return ResourceManager.GetString("TLSserverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.v2ray.com/en/configuration/transport.html.
        /// </summary>
        public static string transportHelpPage {
            get {
                return ResourceManager.GetString("transportHelpPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport settings....
        /// </summary>
        public static string transportsettings {
            get {
                return ResourceManager.GetString("transportsettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTI:.
        /// </summary>
        public static string tti {
            get {
                return ResourceManager.GetString("tti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP Support.
        /// </summary>
        public static string UDPSupport {
            get {
                return ResourceManager.GetString("UDPSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload Core.
        /// </summary>
        public static string unloadcore {
            get {
                return ResourceManager.GetString("unloadcore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update subscription.
        /// </summary>
        public static string updatesubscription {
            get {
                return ResourceManager.GetString("updatesubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uplink capacity:.
        /// </summary>
        public static string uplinkcapacity {
            get {
                return ResourceManager.GetString("uplinkcapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use All.
        /// </summary>
        public static string useall {
            get {
                return ResourceManager.GetString("useall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID:.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TLS.
        /// </summary>
        public static string usetls {
            get {
                return ResourceManager.GetString("usetls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V2Ray Core.
        /// </summary>
        public static string V2RayCore {
            get {
                return ResourceManager.GetString("V2RayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://v2ray.com/en/index.html.
        /// </summary>
        public static string V2RayHomePage {
            get {
                return ResourceManager.GetString("V2RayHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid config files:.
        /// </summary>
        public static string validConfig {
            get {
                return ResourceManager.GetString("validConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View current config.json.
        /// </summary>
        public static string viewconfig {
            get {
                return ResourceManager.GetString("viewconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMess Servers.
        /// </summary>
        public static string VMessServers {
            get {
                return ResourceManager.GetString("VMessServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write buffer size.
        /// </summary>
        public static string writesize {
            get {
                return ResourceManager.GetString("writesize", resourceCulture);
            }
        }
    }
}
