//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var V2Ray = &quot;SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;&quot;;
        ///
        ///var domains = [
        ///	&quot;vpngate.net&quot;,
        ///	&quot;greatfire.org&quot;,
        ///	&quot;tox.im&quot;,
        ///	&quot;proxifier.com&quot;,
        ///	&quot;dnscrypt.org&quot;,
        ///	&quot;atgfw.org&quot;,
        ///	&quot;chinagfw.org&quot;,
        ///	&quot;whatismyip.com&quot;,
        ///	&quot;goagentplus.com&quot;,
        ///	&quot;shadowsocks.org&quot;,
        ///	&quot;falcop.com&quot;,
        ///	&quot;getlantern.org&quot;,
        ///	&quot;furbo.org&quot;,
        ///	&quot;goagentx.com&quot;,
        ///	&quot;github.com&quot;,
        ///	&quot;sourceforge.net&quot;,
        ///	&quot;torproject.org&quot;,
        ///	&quot;hideme.io&quot;,
        ///	&quot;mozilla.org&quot;,
        ///	&quot;shadowx.work&quot;,
        ///	&quot;v2ray.com&quot;,
        ///	&quot;astrill.com&quot;,
        ///
        ///	//Design
        ///	&quot;deviantart.com&quot;,
        ///
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simplepac {
            get {
                return ResourceManager.GetString("simplepac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;sendThrough&quot;:&quot;0.0.0.0&quot;,&quot;mux&quot;:{&quot;enabled&quot;:false,&quot;concurrency&quot;:8},&quot;protocol&quot;:&quot;vmess&quot;,&quot;settings&quot;:{&quot;vnext&quot;:[{&quot;address&quot;:&quot;server.cc&quot;,&quot;users&quot;:[{&quot;id&quot;:&quot;12345678-1234-1234-1234-12345678abcd&quot;,&quot;alterId&quot;:0,&quot;security&quot;:&quot;auto&quot;,&quot;level&quot;:0}],&quot;port&quot;:12345}]},&quot;tag&quot;:&quot;vmess outbound&quot;,&quot;streamSettings&quot;:{&quot;wsSettings&quot;:{&quot;path&quot;:&quot;&quot;,&quot;headers&quot;:{}},&quot;quicSettings&quot;:{&quot;key&quot;:&quot;key&quot;,&quot;security&quot;:&quot;none&quot;,&quot;header&quot;:{&quot;type&quot;:&quot;none&quot;}},&quot;tlsSettings&quot;:{&quot;allowInsecure&quot;:false,&quot;alpn&quot;:[&quot;http\/1.1&quot;],&quot;serverName&quot;:&quot;server.cc&quot;,&quot;allowInsecureCiphers&quot;:false},&quot;httpSet [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vmessjson {
            get {
                return ResourceManager.GetString("vmessjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon vw256 {
            get {
                object obj = ResourceManager.GetObject("vw256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
