//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///            &quot;email&quot;: &quot;love@server.cc&quot;,
        ///            &quot;address&quot;: &quot;server.cc&quot;,
        ///            &quot;port&quot;: 1234,
        ///            &quot;method&quot;: &quot;aes-256-gcm&quot;,
        ///            &quot;password&quot;: &quot;password&quot;,
        ///            &quot;ota&quot;: false,
        ///            &quot;level&quot;: 0
        ///          } 的本地化字符串。
        /// </summary>
        internal static string shadowsockstemplate {
            get {
                return ResourceManager.GetString("shadowsockstemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var V2Ray = &quot;PROXY 127.0.0.1:8001; SOCKS5 127.0.0.1:1081; SOCKS 127.0.0.1:1081; DIRECT;&quot;;
        ///
        ///var domains = [
        ///	&quot;vpngate.net&quot;,
        ///	&quot;greatfire.org&quot;,
        ///	&quot;tox.im&quot;,
        ///	&quot;proxifier.com&quot;,
        ///	&quot;dnscrypt.org&quot;,
        ///	&quot;atgfw.org&quot;,
        ///	&quot;chinagfw.org&quot;,
        ///	&quot;whatismyip.com&quot;,
        ///	&quot;goagentplus.com&quot;,
        ///	&quot;shadowsocks.org&quot;,
        ///	&quot;falcop.com&quot;,
        ///	&quot;getlantern.org&quot;,
        ///	&quot;furbo.org&quot;,
        ///	&quot;goagentx.com&quot;,
        ///	&quot;github.com&quot;,
        ///	&quot;sourceforge.net&quot;,
        ///	&quot;torproject.org&quot;,
        ///	&quot;hideme.io&quot;,
        ///	&quot;mozilla.org&quot;,
        ///	&quot;shadowx.work&quot;,
        ///	&quot;v2ray.com&quot;,
        ///	&quot;astrill.com&quot;,
        ///
        ///	//Design
        ///	&quot;deviantart.com&quot;,
        ///
        ///	&quot;disqus [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string simplepac {
            get {
                return ResourceManager.GetString("simplepac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;sendThrough&quot;:&quot;0.0.0.0&quot;,&quot;mux&quot;:{&quot;enabled&quot;:false,&quot;concurrency&quot;:8},&quot;protocol&quot;:&quot;vmess&quot;,&quot;settings&quot;:{&quot;vnext&quot;:[{&quot;address&quot;:&quot;server.cc&quot;,&quot;users&quot;:[{&quot;id&quot;:&quot;12345678-1234-1234-1234-12345678abcd&quot;,&quot;alterId&quot;:0,&quot;security&quot;:&quot;auto&quot;,&quot;level&quot;:0}],&quot;port&quot;:12345}]},&quot;tag&quot;:&quot;vmess outbound&quot;,&quot;streamSettings&quot;:{&quot;wsSettings&quot;:{&quot;path&quot;:&quot;&quot;,&quot;headers&quot;:{}},&quot;quicSettings&quot;:{&quot;key&quot;:&quot;key&quot;,&quot;security&quot;:&quot;none&quot;,&quot;header&quot;:{&quot;type&quot;:&quot;none&quot;}},&quot;tlsSettings&quot;:{&quot;allowInsecure&quot;:false,&quot;alpn&quot;:[&quot;http\/1.1&quot;],&quot;serverName&quot;:&quot;server.cc&quot;,&quot;allowInsecureCiphers&quot;:false},&quot;httpSet [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string vmessjson {
            get {
                return ResourceManager.GetString("vmessjson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///      &quot;sendThrough&quot;: &quot;0.0.0.0&quot;,
        ///      &quot;mux&quot;: {
        ///        &quot;enabled&quot;: false,
        ///        &quot;concurrency&quot;: 8
        ///      },
        ///      &quot;protocol&quot;: &quot;vmess&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot;vnext&quot;: [
        ///          {
        ///            &quot;address&quot;: &quot;server.cc&quot;,
        ///            &quot;users&quot;: [
        ///              {
        ///                &quot;id&quot;: &quot;12345678-1234-1234-1234-12345678abcd&quot;,
        ///                &quot;alterId&quot;: 0,
        ///                &quot;security&quot;: &quot;auto&quot;,
        ///                &quot;level&quot;: 0
        ///              }
        ///            ],
        ///            &quot;port&quot;: 12345
        ///          }
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string vmesstemplate {
            get {
                return ResourceManager.GetString("vmesstemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon vw256 {
            get {
                object obj = ResourceManager.GetObject("vw256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
