//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayW.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""network"": ""tcp"",
  ""security"": ""none"",
  ""tlsSettings"": {
    ""serverName"": ""v2ray.com"",
    ""allowInsecure"": false
  },
  ""tcpSettings"": {
    ""connectionReuse"": true,
    ""header"": {
      ""type"": ""none""
    }
  },
  ""kcpSettings"": {
    ""mtu"": 1350,
    ""tti"": 20,
    ""uplinkCapacity"": 5,
    ""downlinkCapacity"": 20,
    ""congestion"": false,
    ""readBufferSize"": 1,
    ""writeBufferSize"": 1,
    ""header"": {
      ""type"": ""none""
    }
  },
  ""wsSettings"": {
    ""connectionReuse"": true,
    ""path"": """"
  }
}")]
        public string transportSettings {
            get {
                return ((string)(this["transportSettings"]));
            }
            set {
                this["transportSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string dns {
            get {
                return ((string)(this["dns"]));
            }
            set {
                this["dns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8080")]
        public int localPort {
            get {
                return ((int)(this["localPort"]));
            }
            set {
                this["localPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"address\":\"v2ray.cool\",\"allowPassive\":0,\"alterId\":64,\"network\":0,\"port\":10086,\"r" +
            "emark\":\"test server\",\"userId\":\"23ad6b10-8d1a-40f7-8ad0-e3e35cd38297\",\"security\":" +
            "0}")]
        public string profilesStr {
            get {
                return ((string)(this["profilesStr"]));
            }
            set {
                this["profilesStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool proxyIsOn {
            get {
                return ((bool)(this["proxyIsOn"]));
            }
            set {
                this["proxyIsOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int selectedServerIndex {
            get {
                return ((int)(this["selectedServerIndex"]));
            }
            set {
                this["selectedServerIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool udpSupport {
            get {
                return ((bool)(this["udpSupport"]));
            }
            set {
                this["udpSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int proxyMode {
            get {
                return ((int)(this["proxyMode"]));
            }
            set {
                this["proxyMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int inProtocol {
            get {
                return ((int)(this["inProtocol"]));
            }
            set {
                this["inProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool alarmUnknown {
            get {
                return ((bool)(this["alarmUnknown"]));
            }
            set {
                this["alarmUnknown"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoSetSysProxy
        {
            get
            {
                return ((bool)(this["autoSetSysProxy"]));
            }
            set
            {
                this["autoSetSysProxy"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"enabled\": false,\r\n  \"concurrency\": 8\r\n}")]
        public string mux {
            get {
                return ((string)(this["mux"]));
            }
            set {
                this["mux"] = value;
            }
        }
    }
}
